clone_folder: C:\gtk-build\github\gvsbuild

matrix:
  fast_finish: true

environment:
  global:
    DOWNLOAD_DIR: _download_cache
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd
    PYTHON: C:\Python37\python.exe
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VER: "15"
      PLATFORM: "x64"
      EXTRA_PRJ: "gstreamer"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VER: "16"
      PLATFORM: "x64"
      EXTRA_PRJ: "gstreamer"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x86"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VER: "15"
      PLATFORM: "x86"

build_script:
  - "%PYTHON% build.py build --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% -k --enable-gi --py-wheel --py-egg --python-ver 3.7 --fast-build gtk enchant gtk3-full pycairo pygobject lz4 %EXTRA_PRJ%"
  - "%PYTHON% build.py build --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% -k --fast-build --clean-built --py-wheel --py-egg --python-ver 3.6 pycairo pygobject"
  - "%PYTHON% build.py build --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% -k --fast-build --clean-built --py-wheel --py-egg --python-ver 3.5 pycairo pygobject"
  - set PATH=%PATH%;C:\msys64\usr\bin
  - IF "%PLATFORM%"=="x86" tar.exe -zcf gvsbuild-vs%VS_VER%-%PLATFORM%.tar.gz -C /c/gtk-build/gtk/Win32 release
  - IF "%PLATFORM%"=="x64" tar.exe -zcf gvsbuild-vs%VS_VER%-%PLATFORM%.tar.gz -C /c/gtk-build/gtk/x64 release

artifacts:
  - path: gvsbuild-vs%VS_VER%-%PLATFORM%.tar.gz
  - path: ..\..\logs\gvsbuild-log.txt

cache:
  - '%DOWNLOAD_DIR%'
  - c:\gtk-build\tools

deploy: off

test: off
