[tool.poetry]
name = "gvsbuild"
version = "2022.1.0"
description = "GTK stack for Windows"
authors = ["Ignacio Casal Quinteiro <qignacio@amazon.com>", "Dan Yeaw <dan@yeaw.me>"]
license = "GPL-2.0-only"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Build Tools",
    "Environment :: X11 Applications :: GTK",
    "Operating System :: Microsoft :: Windows",
]

[tool.poetry.dependencies]
python = "^3.8"
lastversion = { version = "^2.4.2", optional = true }
packaging = { version = "^21.3", optional = true }

[tool.poetry.dev-dependencies]
pre-commit = "^2.18.1"

[tool.poetry.extras]
outdated = ["lastversion", "packaging"]

[tool.poetry.scripts]
gvsbuild = 'gvsbuild.main:build'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "lastversion"
ignore_missing_imports = true

[tool.isort]
profile = "black"
skip = ".venv"
