[tool.poetry]
name = "gvsbuild"
version = "2023.10.1"
description = "GTK stack for Windows"
authors = ["Ignacio Casal Quinteiro <qignacio@amazon.com>", "Dan Yeaw <dan@yeaw.me>"]
license = "GPL-2.0-only"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Build Tools",
    "Environment :: X11 Applications :: GTK",
    "Operating System :: Microsoft :: Windows",
]

[tool.poetry.dependencies]
python = "^3.8"
build = ">=0.9,<1.1"
lastversion = { version = ">=2.4.2,<4.0.0", optional = true }
packaging = { version = ">=21.3,<24.0", optional = true }
typer = {extras = ["all"], version = ">=0.6.1,<0.10.0"}

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.1"
pytest = "^7.1.3"
tox = "^4.1.2"

[tool.poetry.extras]
outdated = ["lastversion", "packaging"]

[tool.poetry.scripts]
gvsbuild = 'gvsbuild.main:run'

[[tool.mypy.overrides]]
module = "lastversion"
ignore_missing_imports = true

[tool.isort]
profile = "black"
skip = ".venv"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py{38,39,310,311,312}

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
commands = pytest
deps = pytest
"""

[tool.ruff]
ignore = ["E501"]
line-length = 88
select = [
    "E",
    "F",
    "W",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
